name: Unit App Pipeline

defaults:
  run:
    working-directory: terrform

on: 
  pull_request:
  workflow_dispatch:
  
permissions:
  id-token: write # required for JWT for AWS to authenticate
  contents: read  # required for actions to checkout repo

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
          
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
  terraform-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [setup]

    
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v4
      
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::425669312978:role/github-actions
        
      - name: Terraform Init
        id: init
        continue-on-error: false
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
        
  apply-Changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:  
      - uses: hashicorp/setup-terraform@v2
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::425669312978:role/github-actions
    
      - name: Terraform Init
        id: init
        continue-on-error: false
        run: terraform init
    
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false

    

