name: Unit App Pipeline

defaults:
  run:
    working-directory: terrform

on: [push]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::425669312978:role/github-actions
        
      - run: aws sts get-caller-identity
          
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
  terraform-Plan:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [setup]
    
    steps:
      - uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        id: init
        continue-on-error: true
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        
  apply-Changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:  
      - uses: hashicorp/setup-terraform@v2
    
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false
        working-directory: "terrform"

    

