name: GitHub Actions Demo

on: [push]

defaults:
  run:
    working-directory: "/terrform"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
          
