name: Unit App Pipeline

on: [push]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Plan-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume:  arn:aws:iam::425669312978:role/github-actions
          
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Terraform fmt
        id: fmt
        working-directory: "terrform"
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        working-directory: "terrform"
        id: init
        run: terraform init


          
