name: unit conversion cicd 
defaults:
  run:
    working-directory: terraform
on:
  workflow_dispatch: 
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Setup Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: terraform init

