name: unit conversion cicd 

on:
  workflow_dispatch: 
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Setup Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    
    - name: Terraform fmt
      id: fmt
      working-directory: "/terrform"
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      working-directory: "/terrform"  
      id: init
      run: terraform init
      
    - name: Terraform Plan
      working-directory: "/terrform"
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      
    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
          
