name: unit conversion cicd 

on:
  workflow_dispatch: 
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Setup Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3

    - name: List files in the repository
      run: |
        ls "${{ github.workspace }}"
    
    - name: Terraform fmt
      id: fmt
      working-directory: "{{ github.workspace }}/terrform"
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      working-directory: "/terrform"  
      id: init
      run: terraform init

          
